### PR TITLE
Ergo Structs, middleware using context.Context

### PR DESCRIPTION
**Pull request by husobee**
Inital stab at middleware chaining, using context.Context only.  Initial Ergo data structures, and middleware structures

### CODE REVIEW

**Comment by axdg** [comment]
Had a quick look over this, it seems fine as a starting point. A few points:
 - My thinking is that functions like GetRequest(context.Context), should exist outside of the core of the library. A user who is familiar with using context.Context might want to roll their own functions to do this sort of thing, or prefer to used context directly e.g. `req := ctx.Value(Request)`. Functions like this should be in another optional package (maybe ergoutil)
 - I'm not sure that a background context should be created in the ergo struct itself, but rather in the router before the context is passed to the handler. The [godoc](https://godoc.org/golang.org/x/net/context) says that "Incoming requests to a server should create a Context", and the [original blog post code examples for net/context](https://blog.golang.org/context) call context.Background() inside a handler.

What do you think?

**Comment by husobee** [comment]
I agree that GetRequest type helper functions should be in a different package like ergoutils.  Will modify this PR to reflect that a little later today.

The reasoning behind having the root context live inside of ergo and used during ergo creation is for the times where you might want to have a Value global to the entire service.  Such as a database connection pointer, or, more directly relatable within this code, a middle-ware construct that lives within the context.  With regards to incoming requests creating the context, this is happening within the Ergo.ServeHTTP here: https://github.com/husobee/ergo/blob/proto-ergo/ergo.go#L72

Every connection that gets spawned will create a new context which just happens to have a parent context that includes the middleware datastructure, and the new request.

**Comment by husobee** [comment]
These changes in this latest commit create a middleware position counter which is instantiated per request.  Before all the requests were sharing the same positional counter, which caused failures.  Now, there is a base context that the server has, populates that context with the list of middlewares, then on each request a new context is generated from the base context which includes the request and a middleware position counter.  This allows middlewares to only need a context, and response writer in their signatures, allowing middlewares to have the same function signature of handler functions.

**Comment by husobee** [comment]
@axdg: does this look like a good starting point? have you made any progress on the router?

**Pull request merged**
